Stop running when compile fail

diff --git a/hw5/check b/hw5/check
--- a/hw5/check
+++ b/hw5/check
@@ -18,7 +18,13 @@ function result {
 }
 
 echo '# Compiling...'
-make
+if ! make
+then
+    echo ''
+    echo 'Compile fail.'
+    exit 1
+fi
+echo ''
 
 echo '# Testing SM5 translator'
 
diff --git a/hw6/ex1/check b/hw6/ex1/check
--- a/hw6/ex1/check
+++ b/hw6/ex1/check
@@ -18,7 +18,12 @@ function result {
 }
 
 echo '# Compiling...'
-make
+if ! make
+then
+    echo ''
+    echo 'Compile fail.'
+    exit 1
+fi
 echo ''
 
 echo '# Testing Rozetta: K-- -> Sm5 -> Sonata'
